function plotmeshing(nodes, elements, Bedges, Bnodes)

figure;
patch('faces',elements(:,1:3),'vertices',nodes, ...
    'facecolor','w', ...
    'edgecolor',[.2,.2,.2]) ;
hold on; axis image off;
patch('faces',Bedges(:,1:2),'vertices',Bnodes, ...
    'facecolor','w', ...
    'edgecolor',[.1,.1,.1], ...
    'linewidth',1.5) ;