function plot_rst(nodes, elements, Bedges, Bnodes, etri, nodesDef, BnodesDef, sigma, utot)


figure;
set(gcf, 'Position', get(0, 'Screensize'));
subplot(2,2,1)
    % Netz
    patch('faces',elements(:,1:3),'vertices',nodes, ...
        'facecolor','none', ...
        'facealpha', 1, ...
        'edgecolor',[.2,.2,.2],...
        'edgealpha', 0.3) ;
    hold on; axis image off;
    % Randknoten Fett
    patch('faces',Bedges(:,1:2),'vertices',Bnodes, ...
        'facecolor','none', ...
        'facealpha', 0.6, ...
        'edgecolor', [.2,.2,.2],...
        'edgealpha', 1,...
        'linewidth',1.5) ;
    % Verformte Geometrie
    patch('faces',elements(:,1:3),'vertices',nodesDef, ...
        'FaceVertexCData', utot,'FaceColor','interp', ...
        'facealpha', 0.6, ...
        'edgecolor', [.2,.2,.2],...
        'edgealpha', 0.1) ;
    title('Verformter Zustand');
    % Randknoten Fett
    patch('faces',etri(:,1:2),'vertices',BnodesDef, ...
        'facecolor','none', ...
        'facealpha', 0.6, ...
        'edgecolor', [.2,.2,.2],...
        'edgealpha', 1,...
        'linewidth',1.5) ;
    ax = gca;
    ax.Clipping = 'off';
    colorbar('southoutside'); 
subplot(2,2,2)
    patch('faces',elements(:,1:3),'vertices',nodes, ...
        'FaceVertexCData',sigma(:,1),'FaceColor','flat', ...
        'facealpha', 1, ...
        'edgecolor',[.1,.1,.1],...
        'edgealpha', 0.1);
    hold on; axis image off;
    colorbar('southoutside'); 
    colormap jet
    title('Normalspannungen xx');
    ax = gca;
    ax.Clipping = 'off';
subplot(2,2,3)
    patch('faces',elements(:,1:3),'vertices',nodes, ...
        'FaceVertexCData',sigma(:,2),'FaceColor','flat', ...
        'facealpha', 1, ...
        'edgecolor',[.1,.1,.1],...
        'edgealpha', 0.1);
    hold on; axis image off;
    colorbar('southoutside'); 
    colormap jet
    title('Schubspannungen xy');
    ax = gca;
    ax.Clipping = 'off';
subplot(2,2,4)
    patch('faces',elements(:,1:3),'vertices',nodes, ...
        'FaceVertexCData',sigma(:,3),'FaceColor','flat', ...
        'facealpha', 1, ...
        'edgecolor',[.1,.1,.1],...
        'edgealpha', 0.1);
    hold on; axis image off;
    colorbar('southoutside'); 
    colormap jet
    title('Normalspannungen yy');
    ax = gca;
    ax.Clipping = 'off';